name: Commitlint
run-name: ${{ github.actor }} started the Lint
on: [push, pull_request, workflow_call]
jobs:
  commitlint:
    name: Verify commit message
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      # сохраняем кэш между запусками workflow
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ccache
      - name: Install packages
        run: npm ci
      - name: Check last commit
        if: github.event_name == 'push'
        run: npx commitlint --from HEAD~1 --to HEAD --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
