name: Release
on:
  push:
    tags:
      - 'v\d+'
jobs:
  create-registry:
    name: Create registry
    runs-on: ubuntu-latest
    outputs:
      issueid: ${{ steps.issue.outputs.number }}
      changelog: ${{ steps.changelog.outputs.clean_changelog }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          fetch-depth: 0
      - uses: TriPSs/conventional-changelog-action@v3
        name: Conventional Changelog Action
        id: changelog
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-git-pull: "true"
          output-file: "false"
      - uses: JasonEtco/create-an-issue@v2.9.1
        name: Create an issue
        id: issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          changelog: ${{ steps.changelog.outputs.clean_changelog }}
          tag: ${{ github.ref_name }}
        with:
          assignees: "${{ github.event.release.author.login }}"
          update_existing: true
          search_existing: all
          filename: .github/templates/issue.md
      - uses: izhangzhihao/delete-comment@master
        name: Delete previous comments
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_user_name: github-actions[bot]
          issue_number: ${{ steps.issue.outputs.number }}